name: Deploy to VDS

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to VDS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VDS_HOST }}
        username: ${{ secrets.VDS_USER }}
        key: ${{ secrets.VDS_SSH_KEY }}
        script: |
          cd /var/www/kristal
          
          # Получаем последние изменения
          git pull origin main
          
          # Обновляем зависимости сервера
          cd server
          npm install
          
          # Перезапускаем сервер
          pm2 restart kristal-backend
          
          # Логи
          pm2 logs kristal-backend --lines 50


